version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=andrey
      - DB_NAME=fitness_api
      - REDIS_ADDR=redis:6379  # Добавляем переменную для Redis
    env_file:
      - ./config.env
    volumes:
      - ./config.env:/app/config.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started  # Ждём, пока Redis запустится
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=andrey
      - POSTGRES_DB=fitness_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./medApp.sql:/docker-entrypoint-initdb.d/medApp.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fitness_api"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
